dvh_fam_ungdom:
  target: "{{env_var('DBT_DB_TARGET')}}"
  outputs:
    U:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv04-scan.adeo.no
      port: 1521
      dbname: dwhu1
      service: ccdwhu1_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    R:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv04-scan.adeo.no
      port: 1521
      dbname: dwhpr
      service: dwhr_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
    P:
      type: oracle
      user: "{{env_var('DBT_ENV_SECRET_USER')}}"
      pass: "{{env_var('DBT_ENV_SECRET_PASS')}}"
      protocol: tcp
      host: dmv03-scan.adeo.no
      port: 1521
      dbname: dwhpr
      service: dwh_ha
      schema: "{{env_var('DBT_DB_SCHEMA')}}"
      threads: 10
config:
  send_anonymous_usage_stats: False