version: 2

sources:

  - name: dt_person_arena
    schema: dt_person
    tables:
      - name: dim_person

  - name: kode_verk
    schema: dt_kodeverk
    tables:
      - name: dim_alder
      - name: dim_tid
      - name: dim_geografi

  - name: fam_ungdom
    schema: dvh_fam_ungdom
    tables:
      - name: fam_up_meta_data
      - name: fam_up_fagsak
      - name: fam_up_behandlingsperioder
      - name: fam_up_tilkjent_ytelseperioder
      - name: fam_up_satsperioder
      - name: fam_up_inntektperioder

  - name: dvh_sbs
    schema: dvh_sbs
    tables:
     - name: SAK_YTELSE_DIM_MV